export const GET_USER_INFO="GET_USER_INFO";
export const GET_USER_INFO_SUCCESS="GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED="GET_USER_INFO_FAILED";

export const SET_USER_TOKEN="SET_USER_TOKEN";

export const GET_USER_PLAYLISTS="GET_USER_PLAYLISTS";
export const GET_USER_PLAYLISTS_SUCCESS="GET_USER_PLAYLISTS_SUCCESS";
export const GET_USER_PLAYLISTS_FAILED="GET_USER_PLAYLISTS_FAILED";

export const SHOW_LOADING="SHOW_LOADING";
export const HIDE_LOADING="HIDE_LOADING";

export const GET_RECENT_PLAYLISTS="GET_RECENT_PLAYLISTS";
export const GET_RECENT_PLAYLISTS_SUCCESS="GET_RECENT_PLAYLISTS_SUCCESS";
export const GET_RECENT_PLAYLISTS_FAILED="GET_RECENT_PLAYLISTS_FAILED";

export const GET_CONTENT_HOME="GET_CONTENT_HOME";
export const GET_CONTENT_HOME_SUCCESS="GET_CONTENT_HOME_SUCCESS";
export const GET_CONTENT_HOME_FAILED="GET_CONTENT_HOME_FAILED";

export const GET_TRACKS_PLAYLIST="GET_TRACKS_PLAYLIST";
export const GET_TRACKS_PLAYLIST_SUCCESS="GET_TRACKS_PLAYLIST_SUCCESS";
export const GET_TRACKS_PLAYLIST_FAILED="GET_TRACKS_PLAYLIST_FAILED";

export const SHOW_CONTENT_LOADING="SHOW_CONTENT_LOADING";
export const HIDE_CONTENT_LOADING="HIDE_CONTENT_LOADING";

export const GET_CATEGORY="GET_CATEGORY";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED="GET_CATEGORY_FAILED";